name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'liberica'
          cache: 'gradle'

      - run: ./gradlew jar testClasses
      - run: cd sample && docker-compose up -d db && cd -
      - run: ./gradlew test
      - run: cd sample && docker-compose stop db && cd -
      - run: cd sample && docker-compose build && cd -
      - run: .github/workflows/check-readme-links.sh
